service: hello-pypy2


provider:
  name: aws
  region: eu-central-1

functions:
  hello-pypy2:
    handler: hello.handler
    runtime: provided
    # Use `AWS_ACCOUNT=$(aws sts get-caller-identity | jq -r .Account) sls deploy` to deploy
    # (or replace the following with your account id)
    layers:
      - arn:aws:lambda:eu-central-1:${env:AWS_ACCOUNT}:layer:pypy:2

